config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users
  get '/search' => 'search#search'
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'relationship/follows/:id' => 'relationships#follows',as: 'relationship_follows'
  get 'relationship/followers/:id' => 'relationships#followers' ,as: 'relationship_followers'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  # before_action :ensure_correct_user, only:[:edit]

  def show
    @users = User.all
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
        redirect_to user_path(@user.id)
    else
        render :edit
    end
  end

  # def logout
  #   session[:user_id] = nil
  #   flash[:notice] = "Signed out successfully."
  #   redirect_to root_path
  # end

   private

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_home.html.erb
<p id="notice">
 <%=  notice %>
</p>

<%= render 'books/profile', user: current_user %>

<h3>Books</h3>
<table>
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= attachment_image_tag user, :profile_image, size: "60x60", farmat: 'jpg', fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "show", user_path(user.id) %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved: <br>
    <ul>
    　 <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
    <% end %>
    </ul>
<% end %>


<h3>New book</h3>
<%= form_with model:@book, local:true do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/users/_profile.html.erb
<h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, size: "60x60", farmat: 'jpg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th><th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th><th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
        <%= link_to edit_user_path(user), class: "btn btn-outline-dark btn-block" do %>
          <span class="fas fa-user-cog"></span>
        <% end %>
      <h2 class="mt-3">New book</h2>
      <form action="/books" accept-charset="UTF-8" method="post">
        <input name="utf8" type="hidden" value="✓">
        <input type="hidden" name="authenticity_token" value="wgQUnuGgxB3+oJE8T8FXsjW2nB+Tt7T8Qm2D/CfW2hYPCuqTZjJjkX/rVjZ2FZPGrVZhw/0OQ4tsZAd3iC/gSg==">
        <%= form_with model:@book, local:true do |f| %>
          <div class="form-group">
            <h4>Title</h4>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <h4>Opinion</h4>
            <%= f.text_area :body %>
          </div>
          <div class="form-group">
            <br><%= f.submit 'Create Book', class: 'btn btn-success'%></br>
          </div>
        <% end %>
      </form>
      <%= yield %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this user from being saved: <br>
        <ul>
    　     <% @user.errors.full_messages.each do |message| %>
           <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <p>Name</p>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%>
        </div>
        <div class="form-group">
          <p>Image</p>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        </div>
        <div class="form-group">
        <p>Introduction</p>
        <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction"%>
        </div>
        <%= f.submit "Update User", class: 'btn btn-secondary'%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="container">
  <div class="row">
　　<div class="col">
      <h3>Follower Users</h3>
      <% if @user.follower.count != 0 %>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @user.following_user.where.not(id: current_user.id).each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, size: "60x60", farmat: 'jpg', fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                <td><%= "フォロー数: #{user.follower.count}" %></td>
　　　　　　　  <td><%= "フォロワー数: #{user.followed.count}" %></td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% else %>
        <%= render 'relationships/notice' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%=  notice %></p>
<div class="container">
  <div class="row">
　　<div class="col-md-3">
      <%= render 'books/profile', { user: @user, book: @book } %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Users</h3>
      <table class="table table-hover table-inverse">
         <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size: "60x60", farmat: 'jpg', fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
          <% if @book.errors.any? %>
            <%= @book.errors.count %>errors prohibited this book from being saved: <br>
            <ul>
    　         <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%=  notice %></p>
<div>
<% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved: <br>
    <ul>
    　<% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<div class="container">
  <div class="row">
　　<div class="col-md-3">
      <%= render 'books/profile', { user: @user, book: @book } %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Books</h3>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to attachment_image_tag(@user, :profile_image, size: "60x60", farmat: 'jpg', fallback: "no_image.jpg"), user_path(@user.id) %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td><%= "コメント数：#{book.book_comments.count} " %></td>
              <!--<%# if current_user.id == book.user_id %>-->
              <!--  <td>-->
              <!--    <%#= link_to "Edit", edit_book_path(book.id), class: 'btn btn-success' %>-->
              <!--  </td>-->
              <!--  <td>-->
              <!--    <%#= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?", class: 'btn btn-danger'  %>-->
              <!--  </td>-->
              <!--<%# end %>-->
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>