config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users
  get '/search' => 'search#search'
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'relationship/follows/:id' => 'relationships#follows',as: 'relationship_follows'
  get 'relationship/followers/:id' => 'relationships#followers' ,as: 'relationship_followers'
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  before_action :ensure_correct_user, only:[:edit]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book)
    else
       render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_home.html.erb
<p id="notice">
 <%=  notice %>
</p>

<h3>Books</h3>

<table>
    <thead>
        <tr>
            <th>title</th>
            <th>body</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
        <tr>
            <td><%= book.title %></td>
            <td><%= book.body %></td>
            <td><%= link_to "show", book_path(book.id) %></td>
            <td><%= link_to "edit", edit_book_path(book.id) %></td>
            <td><%= link_to "destroy", books_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<%= render 'books/profile', user: current_user %>

<% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved: <br>
    <ul>
    　 <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
    <% end %>
    </ul>
<% end %>


<h3>New book</h3>
<%= form_with model:@book, local:true do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/books/_profile.html.erb
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, size: "60x60", farmat: 'jpg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th><th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th><th><%= user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to user.follower.count, relationship_follows_path(user.id) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to user.followed.count, relationship_followers_path(user.id) %></th>
　　　　　</tr>
        </tbody>
      </table>
      <% if current_user == user %>
        <%= link_to edit_user_path(user), class: "btn btn-outline-dark btn-block" do %>
          <span class="fas fa-user-cog"></span>
        <% end %>
      <% else %>
        <% if current_user.following?(user) %>
          <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, class: 'btn btn-info' %>
          <% else %>
          <%= link_to 'フォローする', follow_path(user.id), method: :POST, class: 'btn btn-success' %>
        <% end %>
      <% end %>
      <h2 class="mt-3">New book</h2>
      <form action="/books" accept-charset="UTF-8" method="post">
        <input name="utf8" type="hidden" value="✓">
        <input type="hidden" name="authenticity_token" value="wgQUnuGgxB3+oJE8T8FXsjW2nB+Tt7T8Qm2D/CfW2hYPCuqTZjJjkX/rVjZ2FZPGrVZhw/0OQ4tsZAd3iC/gSg==">
        <%= form_with model:book, local:true do |f| %>
          <div class="form-group">
            <h4>Title</h4>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <h4>Opinion</h4>
            <%= f.text_area :body %>
          </div>
          <div class="form-group">
            <br><%= f.submit 'Create Book', class: 'btn btn-success'%></br>
          </div>
        <% end %>
      </form>
      <%= yield %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this book from being saved: <br>
        <ul>
    　     <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p></p>
        <p>Opinion</p>
        <%= f.text_area :body %>
        <p>
        <td><%= f.submit 'Update Book', class: 'btn btn-success'%></td>
        </p>
        <!--<div class="form_group">-->
        <!--  <label for="book_title">Title</label>-->
        <!--  <input class="form-control book_title" type="text" name="book[title]" id="book_title" placeholder="Title">-->
        <!--</div>-->
        <!--<div class="form_group">-->
        <!--  <label for="book_opinion">Opinion</label>-->
        <!--  <textarea class="form-control book_body" name="book[body]" id="book_body" placeholder:"Opinion">-->
        <!--</div>-->
        <!--<div>-->
        <!--  <button type="submit" class="btn btn-success mb-2">Update Book</button>-->
        <!--</div>-->
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"><%=  notice %></p>
<div>
<% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved: <br>
    <ul>
    　<% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<div class="container">
  <div class="row">
　　<div class="col-md-3">
      <%= render 'books/profile', { user: @user, book: @book } %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Books</h3>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to attachment_image_tag(book.user, :profile_image, size: "60x60", farmat: 'jpg', fallback: "no_image.jpg"), user_path(book.user.id) %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td id="favorite-btn_<%=book.id %>">
                <%= render 'favorites/favorite-btn', { book: book } %>
              </td>
              <td><%= "コメント数：#{book.book_comments.count} " %></td>
              <!--<%# if user_signed_in? && current_user.id == book.user_id %>-->
              <!--  <td>-->
              <!--    <%#= link_to "Edit", edit_book_path(book.id), class: 'btn btn-success' %>-->
              <!--  </td>-->
              <!--  <td>-->
              <!--    <%#= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?", class: 'btn btn-danger'  %>-->
              <!--  </td>-->
              <!--<%# end %>-->
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved:
    　 <% @book.errors.full_messages.each do |message| %>
       <%= message %>
    <% end %>
  <% end %>
<%= form_with model: @book, url:'/books', local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<p id="notice"><%=  notice %></p>
<div>
<% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved: <br>
    <ul>
    　<% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<div class="container">
  <div class="row">
　　<div class="col-md-3">
      <%= render 'books/profile', { user: @user, book: @book_new} %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h3>Book detail</h3>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
                <%= link_to attachment_image_tag(@book.user, :profile_image, size: "40x40", farmat: 'jpg', fallback: "no_image.jpg"), user_path(@book.user.id) %>
                <br /><%= link_to @book.user.name, user_path(@book.user.id) %>
            </td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <td id="favorite-btn_<%=@book.id %>">
              <%= render 'favorites/favorite-btn', { book: @book } %>
            </td>
            <% if user_signed_in? && current_user.id == @book.user_id %>
              <<td>
                  <%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-success' %>
                </td>
                <td>
                  <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "Are you sure?", class: 'btn btn-danger'  %>
                </td>
            <% end %>
            <td><%= "コメント数：#{@book.book_comments.count} " %></td>

          </tr>
        </tbody>
      </table>
      <div class="comments">

              <%= render 'book_comments/index', { book_comments: @book.book_comments} %>

      </div>
      <div>
        <%= render 'book_comments/form', { book: @book, book_comment: @book_comment} %>
      </div>
    </div>
  </div>
</div>

app/views/books/top.html.erb
<body>
      <main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>
    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>



</body>